layout_spectrum: 1
typography_spectrum: 0.3942652
color:
  saturation: 0.8512545
  lightness: 0.7526882
  brandStrength: 0.07526882
  rhythmicContrast: 0.453405
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Hpalawan
